spring:
  application:
    name: demo-1
  datasource:
    username: root
    password: ny0204
    url: jdbc:mysql://localhost:3306/sbms
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true